### ISSUE TITLE
consistent semantics of store request APIs

### ISSUE THREAD

**Issue by sevenEng** [me-box/lib-go-databox#1]
in the node version, the response's status code of a store request is checked, all non-2XX codes are considered error and a rejected promise is returned to a client:
https://github.com/me-box/lib-node-databox/blob/master/lib/utils.js#L88

maybe worth doing the same for this two functions too:
https://github.com/me-box/lib-go-databox/blob/master/utils.go#L165
https://github.com/me-box/lib-go-databox/blob/master/utils.go#L200
to make the semantics consistent between these two libs

**Comment by Toshbrown** [comment]
Good spot, thanks. I will get this updated.
