### ISSUE TITLE
coreStoreClient.go observe function error 

### ISSUE THREAD

**Issue by Hyeontaek-Oh** [me-box/lib-go-databox#12]
Hello. I have interests about PDS projects, so I tried to run databox project on my local machine. 

During "make all" , I got error message as follows:

Step 11/16 : RUN make build
 ---> Running in 662f31c3f6d2
rm -rf //src/github.com/docker/docker/vendor/github.com/docker/go-connections > /dev/null
go build -ldflags="-s -w" -o bin/databox *.go
"# github.com/me-box/lib-go-databox"
src/github.com/me-box/lib-go-databox/coreStoreClient.go:188:42: not enough arguments in call to csc.ZestC.Observe
	have (string, string, string, number)
	want (string, string, string, zest.ObserveMode, uint32)
make: *** [Makefile:70: build] Error 2

I think either coreStoreClient or goZestClient should be fixed.

**Comment by Toshbrown** [comment]
Hi, 

This will be fixed in the next minor release, now go 1.11 has module support we will move to using that. So this wont happens in future.

If you check out the code tagged as 0.5.0 the function signatures will match and it should build.
